version: '3'
services:
  postgres:
    image: postgres
    command: 
      - "postgres"
      - "-c" 
      - "max_connections=1000"
      - "-c"
      - "listen_addresses=*"
    restart: on-failure
    environment:
      POSTGRES_DB: xenovox
      POSTGRES_USER: fady
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fady.m.moussa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5500:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

networks:
  dockerNet:
    driver: bridge

volumes:
  pgadmin-data:
  postgres:
    external: false